// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApiSecurityDbContext))]
    [Migration("20260510121558_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Client.Data.IntegrationClientEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPreview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IntegrationClients");
                });

            modelBuilder.Entity("Client.Data.KnownDeliveryTargetEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("AssociatedGuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoCrosspost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IntegrationClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedGuildId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IntegrationClientId", "Name")
                        .IsUnique();

                    b.HasIndex("IntegrationClientId", "TargetId")
                        .IsUnique();

                    b.ToTable("KnownDeliveryTargets");
                });

            modelBuilder.Entity("Client.Data.PermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Root permission",
                            Key = "root"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Allow to read system administrators",
                            Key = "system.admins.read"
                        },
                        new
                        {
                            Id = 101,
                            Description = "Allow to create and modify system administrators",
                            Key = "system.admins.write"
                        },
                        new
                        {
                            Id = 200,
                            Description = "Allow to read API clients",
                            Key = "api.clients.read"
                        },
                        new
                        {
                            Id = 201,
                            Description = "Allow to create and modify API clients",
                            Key = "api.clients.write"
                        },
                        new
                        {
                            Id = 300,
                            Description = "Allow to read known delivery targets",
                            Key = "api.knownTargets.read"
                        },
                        new
                        {
                            Id = 301,
                            Description = "Allow to create and modify known delivery targets",
                            Key = "api.knownTargets.write"
                        });
                });

            modelBuilder.Entity("Client.Data.RolePermissionEntity", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 100
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 101
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 200
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 201
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 300
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 301
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 100
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 200
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 300
                        });
                });

            modelBuilder.Entity("Client.Data.SystemAdministratorEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemManaged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("SystemAdministrators");
                });

            modelBuilder.Entity("Client.Data.SystemRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HierarchyWeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HierarchyWeight = 1000,
                            Name = "Super Administrator"
                        },
                        new
                        {
                            Id = 2,
                            HierarchyWeight = 500,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 3,
                            HierarchyWeight = 100,
                            Name = "Moderator"
                        });
                });

            modelBuilder.Entity("Client.Data.ZabbixCredentialEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AssociatedIntegrationClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedIntegrationClientId")
                        .IsUnique();

                    b.ToTable("ZabbixCredentials");
                });

            modelBuilder.Entity("Client.Data.KnownDeliveryTargetEntity", b =>
                {
                    b.HasOne("Client.Data.SystemAdministratorEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Client.Data.IntegrationClientEntity", "IntegrationClient")
                        .WithMany("KnownDeliveryTargets")
                        .HasForeignKey("IntegrationClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("IntegrationClient");
                });

            modelBuilder.Entity("Client.Data.RolePermissionEntity", b =>
                {
                    b.HasOne("Client.Data.PermissionEntity", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client.Data.SystemRoleEntity", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Client.Data.SystemAdministratorEntity", b =>
                {
                    b.HasOne("Client.Data.SystemAdministratorEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Client.Data.SystemRoleEntity", "Role")
                        .WithMany("Administrators")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Client.Data.ZabbixCredentialEntity", b =>
                {
                    b.HasOne("Client.Data.IntegrationClientEntity", "AssociatedIntegrationClient")
                        .WithOne("ZabbixCredential")
                        .HasForeignKey("Client.Data.ZabbixCredentialEntity", "AssociatedIntegrationClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociatedIntegrationClient");
                });

            modelBuilder.Entity("Client.Data.IntegrationClientEntity", b =>
                {
                    b.Navigation("KnownDeliveryTargets");

                    b.Navigation("ZabbixCredential");
                });

            modelBuilder.Entity("Client.Data.PermissionEntity", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Client.Data.SystemRoleEntity", b =>
                {
                    b.Navigation("Administrators");

                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
